# Builtin
from enum import Enum

class TileType(Enum):
    Empty = ...
    Floor = ...
    Wall = ...
    Obstacle = ...
    Player = ...
    Potion = ...

class LevelConstants:
    level: int
    width: int
    height: int

def create_map(
    level: int,
    seed: int | None = None,
) -> tuple[list[TileType], LevelConstants]: ...
