# Builtin
from enum import Enum

class TileType(Enum):
    Empty = ...
    Floor = ...
    Wall = ...
    Obstacle = ...
    Player = ...
    Potion = ...

def create_map(
    level: int,
    seed: int | None = None,
) -> tuple[list[TileType], tuple[int, int, int]]: ...
