# Builtin
from enum import Enum

class TileType(Enum):
    Empty = ...
    Floor = ...
    Wall = ...
    Obstacle = ...
    Player = ...
    HealthPotion = ...
    Chest = ...

class LevelConstants:
    @property
    def level(self: LevelConstants) -> int: ...
    @property
    def width(self: LevelConstants) -> int: ...
    @property
    def height(self: LevelConstants) -> int: ...
    @property
    def enemy_limit(self: LevelConstants) -> int: ...

def create_map(
    level: int,
    seed: int | None = None,
) -> tuple[list[TileType], LevelConstants]: ...
