version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-dependencies:
        patterns:
          - "*"  # Update all dependencies
    labels:
      - "type: dependency"
      - "status: pending"
    schedule:
      interval: "daily"
  - package-ecosystem: "uv"
    directory: "/"
    groups:
      uv-dependencies:
        patterns:
          - "*"  # Update all dependencies
    labels:
      - "type: dependency"
      - "status: pending"
    schedule:
      interval: "daily"
