# Builtin
from enum import Enum
from typing import Callable, Final, Iterator, SupportsFloat, TypeAlias, TypeVar

# Define some type vars for the registry
_C = TypeVar("_C")
_S = TypeVar("_S")

# Define the action function for callables
ActionFunction: TypeAlias = Callable[[int], float]

# Define the global variables
SPRITE_SCALE: Final[int] = ...
SPRITE_SIZE: Final[int] = ...

class Vec2d:
    x: float
    y: float

    def __init__(self: Vec2d, x: float, y: float) -> None: ...
    def __iter__(self: Vec2d) -> Iterator[SupportsFloat]: ...
    def __mul__(self, other: float) -> Vec2d: ...

class RegistryError(Exception): ...

class AttackAlgorithm(Enum):
    AreaOfEffect = ...
    Melee = ...
    Ranged = ...

class StatusEffectType(Enum):
    TEMP = ...
    TEMP2 = ...

class SteeringBehaviours(Enum):
    Arrive = ...
    Evade = ...
    Flee = ...
    FollowPath = ...
    ObstacleAvoidance = ...
    Pursue = ...
    Seek = ...
    Wander = ...

class SteeringMovementState(Enum):
    Default = ...
    Footprint = ...
    Target = ...

class ComponentBase:
    def has_indicator_bar(self: ComponentBase) -> bool: ...

class SystemBase: ...

class Registry:
    def __init__(self: Registry) -> None: ...
    def create_game_object(
        self: Registry,
        position: Vec2d,
        components: list[ComponentBase],
    ) -> int: ...
    def delete_game_object(self: Registry, game_object_id: int) -> None: ...
    def has_component(
        self: Registry,
        game_object_id: int,
        component: type[ComponentBase],
    ) -> bool: ...
    def get_component(
        self: Registry,
        game_object_id: int,
        component: type[_C],
    ) -> _C: ...
    def update(self: Registry, delta_time: float) -> None: ...
    def add_wall(self: Registry, wall: Vec2d) -> None: ...
    def add_systems(self: Registry) -> None: ...
    def get_system(self: Registry, system: type[_S]) -> _S: ...

def grid_pos_to_pixel(position: Vec2d) -> tuple[float, float]: ...
