name: 🐛 Bug Report
description: Report a bug in Hades
labels: ["type: bug", "status: pending"]
assignees: Aspect1103
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for wanting to report a bug in Hades**

        Please make sure that [this feature wasn't already requested](https://github.com/Aspect1103/Hades/issues?q=is%3Aissue+is%3Aopen+)
        or already implemented in the main branch
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description:
        Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description:
        Provide the steps needed to reproduce this behaviour.
      placeholder:
        1. Go to \[...\].
        2. Click on \[...\].
        3. Move to \[...\].
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description:
        Provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description:
        If applicable, add screenshots to help explain your problem.
      placeholder:
        Add links to cloud storage sites such as [GitHub Gist](https://gist.github.com).
  - type: textarea
    id: computer-specs
    attributes:
      label: Computer specifications
      description:
        Please follow these steps to provide your computer specifications.
      placeholder:
        1. Open the `Run` window by pressing `Win+R` and type `dxdiag`.
        2. Save all the information to a text file via the `Save All
        Information` button.
        3. Upload the saved file to a cloud storage website such as [GitHub Gist](https://gist.github.com).
        4. Provide the link to computer specifications here.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other context about the problem here including any logs files
        if you have them (these are found in the `logs` folder and are
        labelled by date)
