name: ✨ Feature request
description: Suggest an idea for this project
labels: ["type: feature", "status: pending"]
assignees: Aspect1103
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for wanting to report a bug in Hades**

        Please make sure that [this feature wasn't already requested](https://github.com/Aspect1103/Hades/issues?q=is%3Aissue+is%3Aopen+)
        or already implemented in the main branch
  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description:
        Provide a clear and concise description of what your current problem
        is.
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description:
        Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other context, links or screenshots about the feature request
        here. Describe how the feature would be used, why it is needed and what
        it would solve.
