# Builtin
from enum import Enum
from typing import Final, TypeVar

# Define some type vars for the registry
_System = TypeVar("_System")

# Define the global variables
SPRITE_SCALE: Final[int] = ...
SPRITE_SIZE: Final[int] = ...

class RegistryError(Exception): ...

class GameObjectType(Enum):
    Bullet = ...
    Enemy = ...
    Floor = ...
    Player = ...
    Wall = ...
    Goal = ...
    HealthPotion = ...
    Chest = ...
    Shop = ...

class EffectType(Enum):
    Regeneration = ...
    Poison = ...

class SystemBase: ...

class Registry:
    def get_system(self: Registry, system: type[_System]) -> _System: ...
