from __future__ import annotations

# Builtin
from enum import Enum

class TileType(Enum):
    DebugWall = ...
    Empty = ...
    Floor = ...
    Wall = ...
    Obstacle = ...
    Player = ...
    HealthPotion = ...
    ArmourPotion = ...
    HealthBoostPotion = ...
    ArmourBoostPotion = ...
    SpeedBoostPotion = ...
    FireRateBoostPotion = ...

def create_map(
    level: int,
    seed: int | None = None,
) -> tuple[list[TileType], tuple[int, int, int]]: ...
