from __future__ import annotations

# Builtin
from enum import Enum

class TileType(Enum):
    DebugWall = ...
    Empty = ...
    Floor = ...
    Wall = ...
    Obstacle = ...
    Player = ...
    Potion = ...

def create_map(
    level: int,
    seed: int | None = None,
) -> tuple[list[TileType], tuple[int, int, int]]: ...

# TODO: Modify this extension to just have potions generated (without probabilities)
