# Custom
from hades.sprite import HadesSprite
from hades_extensions.ecs import ComponentBase

class Stat(ComponentBase):
    def get_value(self: Stat) -> float: ...
    def set_value(self: Stat, new_value: float) -> None: ...
    def get_max_value(self: Stat) -> float: ...

class Armour(Stat): ...
class Health(Stat): ...

class KinematicComponent(ComponentBase):
    def get_position(self: KinematicComponent) -> tuple[float, float]: ...
    def get_velocity(self: KinematicComponent) -> tuple[float, float]: ...
    def set_rotation(self: KinematicComponent, angle: float) -> None: ...

class PythonSprite(ComponentBase):
    sprite: HadesSprite
